---
- name: Развертывание portainer
  hosts: localhost,all
  vars:
    my_variable: "Пример значения переменной"
    nginx_ver: "1.18.0"
  tasks:
    - name: Создание хранилища данных для Portainer
      command: docker volume create portainer_data
      args:
        warn: no

    - name: Запуск Portainer
      docker_container:
        name: portainer
        image: portainer/portainer-ce
        state: started
        restart_policy: always
        published_ports:
          - "9000:9000"
          - "9443:9443"
        env:
          TZ: Europe/Moscow
        volumes:
          - "/var/run/docker.sock:/var/run/docker.sock"
          - "portainer_data:/data"
