---
- name: Развертывание mosquitto
  hosts: all,localhost
  tasks:
    - name: Создание хранилища данных для mosquitto
      command: docker volume create mosquitto_data
      args:
        warn: no
    - name: Создание хранилища настроек для mosquitto
      command: docker volume create mosquitto_config
      args:
        warn: no
    - name: Создание хранилища логов для mosquitto
      command: docker volume create mosquitto_log
      args:
        warn: no
    - name: Запуск mosquitto
      docker_container:
        name: mosquitto
        image: eclipse-mosquitto
        state: started
        restart_policy: unless-stopped
        published_ports:
         - "1883:1883/tcp"
         - "9001:9001"
        env:
         TZ: Europe/Moscow
        volumes:
         - mosquitto_config:/mosquitto/config
         - mosquitto_data:/mosquitto/data
         - mosquitto_log:/mosquitto/log
        tty: true